--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06.06.2019 21:23:23
-- Server version: 5.5.5-10.3.13-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO app.comments(id, name, date, message, path, imagename) VALUES
(1, 'Валентин', '2019-05-20T10:01:01+03:00', 'Первый пошёл!', './images/', '001.jpg'),
(2, 'Сергей', '2019-05-20T10:02:01+03:00', 'Второй пошёл!', './images/', '002.jpg'),
(3, 'Анатолий', '2019-05-20T10:03:01+03:00', 'Третий пошёл!', './images/', '003.jpg'),
(4, 'Владимир', '2019-05-20T10:04:01+03:00', 'Четвертый пошёл!', './images/', '004.jpg'),
(5, 'Андрей', '2019-05-20T10:05:01+03:00', 'Пятый пошёл!', './images/', '005.jpg');