--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 06.06.2019 21:23:25
-- Server version: 5.5.5-10.3.13-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO app.pictures(id, path, size, name, view, click, description) VALUES
(9, './images/', 298496, '001.jpg', 1, 1, NULL),
(10, './images/', 107006, '002.jpg', 0, 0, NULL),
(11, './images/', 322249, '003.jpg', 1, 1, NULL),
(12, './images/', 83737, '004.jpg', 0, 0, NULL),
(13, './images/', 196750, '005.jpg', 1, 1, NULL),
(14, './images/', 170219, '006.jpg', 5, 5, NULL),
(15, './images/', 171227, '007.jpg', 0, 0, NULL),
(16, './images/', 153488, '008.jpg', 0, 0, NULL),
(17, './images/', 232606, '009.jpg', 1, 1, NULL),
(18, './images/', 214796, '010.jpg', 1, 1, NULL),
(19, './images/', 75888, '011.jpg', 1, 1, NULL),
(20, './images/', 136859, '012.jpg', 0, 0, NULL),
(21, './images/', 203667, '013.jpg', 0, 0, NULL),
(22, './images/', 171190, '014.jpg', 0, 0, NULL),
(23, './images/', 68720, '015.jpg', 0, 0, NULL),
(24, './images/', 164153, '016.jpg', 0, 0, NULL);